import React, { useState, useEffect } from 'react';
import { View, Text, ScrollView, TouchableOpacity, TextInput, ActivityIndicator, Alert, KeyboardAvoidingView, Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ChevronLeft, Save, Image as ImageIcon, Briefcase, Phone, User } from 'lucide-react-native';
import { supabase } from '../supabaseStorage';

const CreateTeacherScreen = ({ navigation, route }: any) => {
    // Check if we are in Edit Mode
    const teacherToEdit = route.params?.teacherToEdit;
    const isEditing = !!teacherToEdit;

    // Form States
    const [name, setName] = useState('');
    const [surname, setSurname] = useState('');
    const [phone, setPhone] = useState('');
    const [branch, setBranch] = useState(''); // New field for teacher
    const [photoUrl, setPhotoUrl] = useState('');
    const [gender, setGender] = useState<'Kız' | 'Erkek' | null>(null);

    const [loading, setLoading] = useState(false);

    // Populate fields if editing
    useEffect(() => {
        if (teacherToEdit) {
            // Split name if possible
            const names = (teacherToEdit.name || '').split(' ');
            if (names.length > 1) {
                setSurname(names.pop() || '');
                setName(names.join(' '));
            } else {
                setName(teacherToEdit.name || '');
            }

            setPhone(teacherToEdit.phone || '');
            setBranch(teacherToEdit.branch || '');
            setPhotoUrl(teacherToEdit.avatar_url || ''); // Supabase profiles usually use avatar_url
            if (teacherToEdit.gender === 'Kız' || teacherToEdit.gender === 'Erkek') {
                setGender(teacherToEdit.gender);
            }
        }
    }, [teacherToEdit]);

    const handleSave = async () => {
        if (!name || !phone) {
            Alert.alert('Eksik Bilgi', 'Lütfen en az Ad, Soyad ve Telefon bilgilerini giriniz.');
            return;
        }

        setLoading(true);
        try {
            const fullName = `${name} ${surname}`.trim();

            // Prepare Data Payload
            // Assuming table is 'profiles' and role is 'teacher'
            const teacherData: any = {
                name: fullName,
                phone: phone,
                branch: branch || null,
                avatar_url: photoUrl || null,
                role: 'teacher',
                gender: gender || null,
                login_id: isEditing ? teacherToEdit.login_id : `T${Date.now().toString().slice(-6)}`,
                password: isEditing ? teacherToEdit.password : '123456', // Default password for initial creation
            };

            let error;
            if (isEditing) {
                // Update
                const { error: updateError } = await supabase
                    .from('profiles')
                    .update(teacherData)
                    .eq('id', teacherToEdit.id);
                error = updateError;
            } else {
                // Create
                // IMPORTANT: Creating a profile usually requires an Auth ID if using RLS linked to Auth.
                // However, user setup usually allows creating profiles directly if not using strict Auth triggers.
                // If strict auth is used, we might need to create an Auth user first.
                // But the user asked for "Account creation" later. So maybe we just insert into profiles for now.
                // If profiles.id is UUID and references auth.users, we cannot insert here without an auth user.
                // Let's assume we can insert or we generate a random UUID if not constrained.
                // BUT usually profiles.id IS the auth.uid.

                // FALLBACK STRATEGY: 
                // If we can't create a profile without auth, we might need to skip this or use a 'teachers' table if it exists.
                // The prompt says "Account & Password Operations" are next.
                // I will try to insert into 'profiles'. If it fails due to FK, I will alert the user.
                // Alternatively, maybe there is a 'teachers' table? Previous conversation mentioned 'profiles' with role='teacher'.

                // Let's try inserting into 'profiles'. If UUID is generated by DB, it might work.

                const { error: insertError } = await supabase.from('profiles').insert(teacherData);
                error = insertError;
            }

            if (error) {
                console.error("Supabase Error:", error);
                if (error.code === '42703' || error.code === 'PGRST204') {
                    // Fallback: Retry with ONLY basic fields
                    const basicData = {
                        name: fullName,
                        role: 'teacher'
                    };

                    let retryError;
                    if (isEditing) {
                        const { error: ue } = await supabase.from('profiles').update(basicData).eq('id', teacherToEdit.id);
                        retryError = ue;
                    } else {
                        const { error: ie } = await supabase.from('profiles').insert(basicData);
                        retryError = ie;
                    }

                    if (retryError) {
                        Alert.alert('Kritik Hata', 'Temel kayıt bile oluşturulamadı: ' + retryError.message);
                        return;
                    }

                    Alert.alert(
                        'Kısmi Başarı',
                        'Kayıt oluşturuldu ancak veritabanı şeması eksik olduğu için (branş, telefon vb.) detaylı bilgiler kaydedilemedi.'
                    );
                    navigation.goBack();
                    return;
                } else {
                    throw error;
                }
            }

            Alert.alert('Başarılı', `Öğretmen kaydı ${isEditing ? 'güncellendi' : 'oluşturuldu'}.`, [
                { text: 'Tamam', onPress: () => navigation.goBack() }
            ]);
        } catch (error: any) {
            console.error(error);
            Alert.alert('Hata', 'İşlem başarısız: ' + error.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <SafeAreaView style={{ flex: 1, backgroundColor: '#fdfdfd' }}>
            {/* ELEGANT HEADER */}
            <View style={{ padding: 20, flexDirection: 'row', alignItems: 'center', backgroundColor: '#fdfdfd', borderBottomWidth: 1, borderBottomColor: '#f1f5f9' }}>
                <TouchableOpacity onPress={() => navigation.goBack()} style={{ marginRight: 16 }}>
                    <ChevronLeft size={28} color="#475569" strokeWidth={1.5} />
                </TouchableOpacity>
                <Text style={{ fontSize: 20, fontWeight: '300', color: '#0f172a', letterSpacing: -0.5 }}>
                    {isEditing ? 'Öğretmen Düzenle' : 'Yeni Öğretmen Kaydı'}
                </Text>
            </View>

            <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={{ flex: 1 }}>
                <ScrollView contentContainerStyle={{ padding: 24, paddingBottom: 100 }} showsVerticalScrollIndicator={false}>

                    {/* TEACHER INFO SECTION */}
                    <View style={{ marginBottom: 32 }}>
                        <Text style={{ fontSize: 12, fontWeight: '700', color: '#3b82f6', marginBottom: 16, textTransform: 'uppercase', letterSpacing: 1 }}>Öğretmen Bilgileri</Text>

                        <View style={{ gap: 16 }}>
                            {/* PHOTO URL & GENDER */}
                            <View style={{ flexDirection: 'row', gap: 12 }}>
                                <View style={{ flex: 1 }}>
                                    <Text style={{ fontSize: 12, fontWeight: '600', color: '#64748b', marginBottom: 6 }}>FOTOĞRAF URL (Opsiyonel)</Text>
                                    <View style={{ flexDirection: 'row', alignItems: 'center', backgroundColor: 'white', borderRadius: 10, borderWidth: 1, borderColor: '#e2e8f0' }}>
                                        <View style={{ paddingLeft: 12 }}>
                                            <ImageIcon size={16} color="#94a3b8" />
                                        </View>
                                        <TextInput
                                            value={photoUrl}
                                            onChangeText={setPhotoUrl}
                                            placeholder="https://..."
                                            placeholderTextColor="#94a3b8"
                                            style={{ flex: 1, padding: 12, fontSize: 14, color: '#1e293b' }}
                                        />
                                    </View>
                                </View>
                                <View style={{ width: 120 }}>
                                    <Text style={{ fontSize: 12, fontWeight: '600', color: '#64748b', marginBottom: 6 }}>CİNSİYET</Text>
                                    <View style={{ flexDirection: 'row', backgroundColor: 'white', borderRadius: 10, borderWidth: 1, borderColor: '#e2e8f0', padding: 4 }}>
                                        <TouchableOpacity
                                            onPress={() => setGender('Kız')}
                                            style={{ flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 8, borderRadius: 6, backgroundColor: gender === 'Kız' ? '#fce7f3' : 'transparent' }}
                                        >
                                            <Text style={{ fontSize: 12, fontWeight: '600', color: gender === 'Kız' ? '#db2777' : '#94a3b8' }}>Kız</Text>
                                        </TouchableOpacity>
                                        <TouchableOpacity
                                            onPress={() => setGender('Erkek')}
                                            style={{ flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 8, borderRadius: 6, backgroundColor: gender === 'Erkek' ? '#e0f2fe' : 'transparent' }}
                                        >
                                            <Text style={{ fontSize: 12, fontWeight: '600', color: gender === 'Erkek' ? '#0284c7' : '#94a3b8' }}>Erkek</Text>
                                        </TouchableOpacity>
                                    </View>
                                </View>
                            </View>

                            <View style={{ flexDirection: 'row', gap: 12 }}>
                                <View style={{ flex: 1 }}>
                                    <Text style={{ fontSize: 12, fontWeight: '600', color: '#64748b', marginBottom: 6 }}>AD</Text>
                                    <TextInput
                                        value={name}
                                        onChangeText={setName}
                                        placeholder="Ayşe"
                                        placeholderTextColor="#94a3b8"
                                        style={{ backgroundColor: 'white', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 10, padding: 14, fontSize: 15, color: '#1e293b' }}
                                    />
                                </View>
                                <View style={{ flex: 1 }}>
                                    <Text style={{ fontSize: 12, fontWeight: '600', color: '#64748b', marginBottom: 6 }}>SOYAD</Text>
                                    <TextInput
                                        value={surname}
                                        onChangeText={setSurname}
                                        placeholder="Yılmaz"
                                        placeholderTextColor="#94a3b8"
                                        style={{ backgroundColor: 'white', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 10, padding: 14, fontSize: 15, color: '#1e293b' }}
                                    />
                                </View>
                            </View>

                            <View>
                                <Text style={{ fontSize: 12, fontWeight: '600', color: '#64748b', marginBottom: 6 }}>BRANŞ / ALAN</Text>
                                <View style={{ flexDirection: 'row', alignItems: 'center', backgroundColor: 'white', borderRadius: 10, borderWidth: 1, borderColor: '#e2e8f0' }}>
                                    <View style={{ paddingLeft: 14 }}>
                                        <Briefcase size={18} color="#94a3b8" />
                                    </View>
                                    <TextInput
                                        value={branch}
                                        onChangeText={setBranch}
                                        placeholder="Matematik, Sınıf Öğretmeni vb."
                                        placeholderTextColor="#94a3b8"
                                        style={{ flex: 1, padding: 14, fontSize: 15, color: '#1e293b' }}
                                    />
                                </View>
                            </View>

                            <View>
                                <Text style={{ fontSize: 12, fontWeight: '600', color: '#64748b', marginBottom: 6 }}>TELEFON</Text>
                                <View style={{ flexDirection: 'row', alignItems: 'center', backgroundColor: 'white', borderRadius: 10, borderWidth: 1, borderColor: '#e2e8f0' }}>
                                    <View style={{ paddingLeft: 14 }}>
                                        <Phone size={18} color="#94a3b8" />
                                    </View>
                                    <TextInput
                                        value={phone}
                                        onChangeText={setPhone}
                                        placeholder="05XX XXX XX XX"
                                        placeholderTextColor="#94a3b8"
                                        keyboardType="phone-pad"
                                        style={{ flex: 1, padding: 14, fontSize: 15, color: '#1e293b' }}
                                    />
                                </View>
                            </View>

                            <Text style={{ fontSize: 11, color: '#64748b', fontStyle: 'italic', marginTop: 4 }}>
                                Not: Bu öğretmen için sistem girişi ve şifre işlemleri 'Hesap & Şifre İşlemleri' menüsünden yapılacaktır.
                            </Text>
                        </View>
                    </View>

                </ScrollView>

                {/* BOTTOM ACTION */}
                <View style={{ padding: 20, backgroundColor: '#fdfdfd', borderTopWidth: 1, borderTopColor: '#f1f5f9' }}>
                    <TouchableOpacity
                        onPress={handleSave}
                        disabled={loading}
                        style={{
                            backgroundColor: '#3b82f6',
                            paddingVertical: 18,
                            borderRadius: 12,
                            flexDirection: 'row',
                            alignItems: 'center',
                            justifyContent: 'center',
                            gap: 10,
                            shadowColor: '#3b82f6',
                            shadowOffset: { width: 0, height: 4 },
                            shadowOpacity: 0.1,
                            shadowRadius: 10,
                            elevation: 4
                        }}
                    >
                        {loading ? <ActivityIndicator color="white" /> : (
                            <>
                                <Save size={20} color="white" />
                                <Text style={{ color: 'white', fontSize: 16, fontWeight: '600', letterSpacing: 0.5 }}>
                                    {isEditing ? 'GÜNCELLE' : 'KAYDET'}
                                </Text>
                            </>
                        )}
                    </TouchableOpacity>
                </View>
            </KeyboardAvoidingView>
        </SafeAreaView>
    );
};

export default CreateTeacherScreen;
